apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: foobar
spec:
  secretStoreRef:
    name: vault
    kind: SecretStore
  target:
    name: foobar
  refreshInterval: 5s
  data:
    - secretKey: hello
      remoteRef:
        key: /foo/bar
        property: hello
