# See https://external-secrets.io/latest/provider/fake/
apiVersion: external-secrets.io/v1beta1
kind: ClusterSecretStore
metadata:
  name: fake
spec:
  provider:
    fake:
      data:
        - key: "/foo/bar"
          value: "World"
